[metadata]
name = colcon-ros-lake
version = 0.1.0
url = https://github.com/SEIL-ISR/colcon-ros-lake
maintainer = Ryan Matheu
maintainer_email = rmatheu@umd.edu
classifiers =
    Development Status :: 3 - Alpha
    Environment :: Plugins
    Intended Audience :: Developers
    License :: OSI Approved :: Apache Software License
    Operating System :: POSIX :: Linux
    Programming Language :: Python
    Topic :: Software Development :: Build Tools
license = Apache License, Version 2.0
description = Extension for colcon to build Lean 4 packages with Lake, plain or ament.
long_description = file: README.md
long_description_content_type = text/markdown
keywords = colcon lean lake ros

[options]
python_requires = >=3.8
install_requires =
  colcon-core>=0.12.0
  colcon-ros>=0.3.0
packages = find:
zip_safe = false

[options.entry_points]
colcon_core.package_identification =
    lake = colcon_ros_lake.package_identification.lake:LakePackageIdentification
colcon_core.task.build =
    lake = colcon_ros_lake.task.lake.build:LakeBuildTask
    ros.ament_lake = colcon_ros_lake.task.ament_lake.build:AmentLakeBuildTask
colcon_core.task.test =
    lake = colcon_ros_lake.task.lake.test:LakeTestTask
    ros.ament_lake = colcon_ros_lake.task.ament_lake.test:AmentLakeTestTask
console_scripts =
    lake-ament-build = colcon_ros_lake.cli:main

[flake8]
max-line-length = 99
